name: docs site
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
      - run: yarn install --frozen-lockfile
      - name: Configure pages
        uses: actions/configure-pages@v2
      - name: Build site
        run: yarn build:docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: site
      - name: Deploy pages
        id: deployment
        uses: actions/deploy-pages@v1
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
concurrency:
  group: deploy-docs-site
  cancel-in-progress: true
on:
  push:
    branches:
      - main
